"""Shared domain constants for Sentinel API."""

from decimal import Decimal


ACADEMIC_STANDING_EXCELLENT = "excellent"
ACADEMIC_STANDING_GREAT = "great"
ACADEMIC_STANDING_AVERAGE = "average"
ACADEMIC_STANDING_POOR = "poor"

ACADEMIC_STANDING_CHOICES = [
    (ACADEMIC_STANDING_EXCELLENT, "Excellent"),
    (ACADEMIC_STANDING_GREAT, "Great"),
    (ACADEMIC_STANDING_AVERAGE, "Average"),
    (ACADEMIC_STANDING_POOR, "Poor"),
]

ACADEMIC_STANDING_VALUES = [
    ACADEMIC_STANDING_EXCELLENT,
    ACADEMIC_STANDING_GREAT,
    ACADEMIC_STANDING_AVERAGE,
    ACADEMIC_STANDING_POOR,
]

PRIOR_ACADEMIC_STANDING_SCORES = {
    ACADEMIC_STANDING_EXCELLENT: Decimal("100"),
    ACADEMIC_STANDING_GREAT: Decimal("85"),
    ACADEMIC_STANDING_AVERAGE: Decimal("70"),
    ACADEMIC_STANDING_POOR: Decimal("50"),
}
